[package]
name = "rsteg-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Command-line tool for rsteg — embed and extract hidden payloads in BMP, PNG, WAV."
readme = "../../README.md"
keywords = ["steganography", "stego", "lsb", "cli", "hiding"]
categories = ["command-line-utilities", "cryptography", "encoding"]

[[bin]]
name = "rsteg"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
rsteg-core        = { path = "../rsteg-core", version = "=0.1.0" }
rsteg-bmp         = { path = "../rsteg-bmp", version = "=0.1.0" }
rsteg-wav         = { path = "../rsteg-wav", version = "=0.1.0" }
rsteg-png         = { path = "../rsteg-png", version = "=0.1.0" }
rsteg-crypto-aead = { path = "../rsteg-crypto-aead", version = "=0.1.0" }
lexopt            = "0.3"

[dev-dependencies]
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }
